#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python3 -m inventory.main &

python3 -m inventory.rabbit.consumer &

# Wait for any process to exit
wait -n

# Exit with status of process that exited first
exit $?